In [2]:
import numpy as np

1. np.array() – NumPy Dizisi Oluşturma


In [3]:
arr = np.array([1, 2, 3, 4, 5])
print("1. NumPy Dizisi:")
print(arr)


1. NumPy Dizisi:
[1 2 3 4 5]


2. np.zeros() & np.ones() – Sıfır ve Birlerden Oluşan Diziler


In [4]:
zeros_arr = np.zeros((3, 3))
ones_arr = np.ones((2, 4))
print("\n2. 3x3 Sıfır Dizisi:")
print(zeros_arr)
print("\n2. 2x4 Birler Dizisi:")
print(ones_arr)


2. 3x3 Sıfır Dizisi:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

2. 2x4 Birler Dizisi:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


3. np.arange() – Belirli Aralıkta Sayı Dizisi


In [5]:
arange_arr = np.arange(0, 10, 2)
print("\n3. 0'dan 10'a kadar 2 artan dizi:")
print(arange_arr)



3. 0'dan 10'a kadar 2 artan dizi:
[0 2 4 6 8]


4. np.linspace() – İki Değer Arasında Eşit Aralıklı Sayılar


In [7]:
linspace_arr = np.linspace(0, 1, 5)
print("\n4. 0 ile 1 arasında 5 eşit parça:")
print(linspace_arr)


4. 0 ile 1 arasında 5 eşit parça:
[0.   0.25 0.5  0.75 1.  ]


5. np.random.rand() – Rastgele Değerlerden Oluşan Dizi


In [9]:
random_arr = np.random.rand(3, 3)
print("\n5. 3x3 Rastgele Sayılar:")
print(random_arr)



5. 3x3 Rastgele Sayılar:
[[0.19684511 0.10803598 0.09716685]
 [0.82238911 0.64797746 0.04582444]
 [0.66423061 0.6808745  0.68396687]]


6. np.reshape() – Diziyi Yeniden Şekillendirme


In [10]:
reshaped_arr = np.arange(1, 10).reshape(3, 3)
print("\n6. 1-9 Arası Sayılar ile 3x3 Dizi:")
print(reshaped_arr)



6. 1-9 Arası Sayılar ile 3x3 Dizi:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


7. np.max(), np.min(), np.mean(), np.sum() – Temel İstatistiksel İşlemler


In [11]:
sample_arr = np.array([10, 20, 30, 40, 50])
print("\n7. Max:", np.max(sample_arr))
print("   Min:", np.min(sample_arr))
print("   Mean (Ortalama):", np.mean(sample_arr))
print("   Sum (Toplam):", np.sum(sample_arr))



7. Max: 50
   Min: 10
   Mean (Ortalama): 30.0
   Sum (Toplam): 150


8. np.eye() – Birim Matris Oluşturma


In [12]:
identity_matrix = np.eye(4)
print("\n8. 4x4 Birim Matris:")
print(identity_matrix)


8. 4x4 Birim Matris:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


9. np.dot() – Matris Çarpımı


In [13]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
dot_product = np.dot(A, B)
print("\n9. Matris Çarpımı A * B:")
print(dot_product)



9. Matris Çarpımı A * B:
[[19 22]
 [43 50]]


10. np.where() – Belirli Bir Koşula Göre Elemanları Seçme


In [14]:
cond_arr = np.array([10, 15, 20, 25, 30])
result = np.where(cond_arr > 20, "Büyük", "Küçük veya Eşit")
print("\n10. 20'den Büyük Olanlara 'Büyük' Yazdırma:")
print(result)



10. 20'den Büyük Olanlara 'Büyük' Yazdırma:
['Küçük veya Eşit' 'Küçük veya Eşit' 'Küçük veya Eşit' 'Büyük' 'Büyük']
